# Generated by Django 5.2.12 on 2026-04-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS core_historicalplatformsettings",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
