# Generated by Django 5.2.12 on 2026-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecipientaddress",
            name="name",
            field=models.CharField(blank=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="recipientaddress",
            name="name",
            field=models.CharField(blank=True, verbose_name="名称"),
        ),
    ]
