# Generated by Django 5.2.12 on 2026-04-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_gather_period_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gather_period",
            field=models.PositiveIntegerField(
                blank=True,
                default=1440,
                help_text="首次充值后顺延该时间归集；后续同地址同链同币充值会重新顺延",
                verbose_name="自动归集周期(分钟)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                help_text="到期后达到该阈值才归集；0 表示到期即归集",
                max_digits=16,
                verbose_name="自动归集价值(USD)",
            ),
        ),
    ]
