# Generated by Django 5.2.12 on 2026-04-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_historicalrecipientaddress_name_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS projects_historicalproject",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS projects_historicalrecipientaddress",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
