# Generated by Codex on 2026-05-05

from django.db import migrations


def backfill_active_tron_usdt_watch_cursors(apps, schema_editor):
    ChainToken = apps.get_model("currencies", "ChainToken")
    TronWatchCursor = apps.get_model("tron", "TronWatchCursor")
    db_alias = schema_editor.connection.alias

    mappings = (
        ChainToken.objects.using(db_alias)
        .filter(
            chain__active=True,
            chain__type="tron",
            crypto__symbol="USDT",
            crypto__active=True,
        )
        .exclude(address="")
        .values("chain_id", "address")
    )
    for mapping in mappings.iterator():
        TronWatchCursor.objects.using(db_alias).get_or_create(
            chain_id=mapping["chain_id"],
            contract_address=mapping["address"],
            defaults={
                "last_scanned_block": 0,
                "last_safe_block": 0,
                "enabled": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("tron", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            backfill_active_tron_usdt_watch_cursors,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
