# Generated by Django 5.2.12 on 2026-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="failed_collection_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="collect_deposit 返回 False 的累计次数；达到阈值后 gather_deposits 跳过该笔，等待人工介入",
                verbose_name="归集失败计数",
            ),
        ),
    ]
