# Generated by Django 5.2.12 on 2026-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="evm_log_max_block_range",
            field=models.PositiveIntegerField(
                default=10,
                help_text="EVM 扫描器单次 eth_getLogs 请求允许覆盖的最大区块数。",
                verbose_name="EVM 单次日志请求最大区块数",
            ),
        ),
    ]
