# Generated by Codex on 2026-04-25

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_chain_evm_log_max_block_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="onchaintransfer",
            name="block_hash",
            field=common.fields.HashField(
                blank=True,
                null=True,
                unique=False,
                verbose_name="区块哈希",
            ),
        ),
    ]
