# Generated by Codex on 2026-05-04

from django.db import migrations
from django.db import models


def delete_existing_native_scan_cursors(apps, schema_editor):
    EvmScanCursor = apps.get_model("evm", "EvmScanCursor")
    EvmScanCursor.objects.filter(scanner_type="native_direct").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0004_onchaintransfer_block_hash"),
        ("evm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="open_native_scanner",
            field=models.BooleanField(
                default=False,
                help_text="仅 EVM 链有效；关闭时会删除原生币扫描游标，重新开启后从新游标开始扫描。",
                verbose_name="开启原生币扫描",
            ),
        ),
        migrations.RunPython(
            delete_existing_native_scan_cursors,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
