# Generated by Codex on 2026-05-05

from django.db import migrations, models


def clear_tron_rpc(apps, schema_editor):
    Chain = apps.get_model("chains", "Chain")
    Chain.objects.using(schema_editor.connection.alias).filter(type="tron").update(
        rpc=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0005_chain_open_native_scanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="tron_api_key",
            field=models.CharField(blank=True, default="", verbose_name="Tron API Key"),
        ),
        migrations.RunPython(clear_tron_rpc, reverse_code=migrations.RunPython.noop),
    ]
