# Generated by Django 5.2.12 on 2026-05-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0009_add_create2_factory_and_transfer_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcasttask",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rpc_rejected", "节点拒绝"),
                    ("insufficient_balance", "余额不足"),
                    ("fee_too_low", "手续费过低"),
                    ("execution_reverted", "链上执行回退"),
                    ("expected_transfer_missing", "链上执行成功但预期资产移动缺失"),
                    ("utxo_conflict", "UTXO 冲突"),
                    ("double_spend", "双花冲突"),
                ],
                default="",
                max_length=64,
                verbose_name="失败原因",
            ),
        ),
    ]
