#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [[ "${SIGNER_BACKEND:-remote}" != "remote" ]]; then
  >&2 echo 'Signer preflight failed: main app now requires SIGNER_BACKEND=remote'
  exit 1
fi

if [[ "${SIGNER_ENFORCE_PRECHECKS:-true}" != "true" ]]; then
  >&2 echo 'Signer preflight skipped: SIGNER_ENFORCE_PRECHECKS is disabled'
  exit 0
fi

>&2 echo 'Running signer service preflight checks'
python /app/manage.py check_signer_service
