#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

wait-for-it "${POSTGRES_HOST:-django-db}:${POSTGRES_PORT:-5432}" -t 30
>&2 echo 'PostgreSQL is available'

wait-for-it "${REDIS_HOST:-redis}:${REDIS_PORT:-6379}" -t 30
>&2 echo 'Redis is available'

exec "$@"
