# Generated by Django 5.2.12 on 2026-04-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evmbroadcasttask",
            name="completed",
        ),
    ]
