# Generated by Django 5.2.12 on 2026-05-16 15:30

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0010_alter_broadcasttask_failure_reason"),
        ("currencies", "0001_initial"),
        ("evm", "0004_add_tx_kind_check_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractDeployCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factory_address",
                    common.fields.EvmAddressField(db_index=True, max_length=42),
                ),
                (
                    "collector_address",
                    common.fields.EvmAddressField(db_index=True, max_length=42),
                ),
                (
                    "vault_address",
                    common.fields.EvmAddressField(db_index=True, max_length=42),
                ),
                ("salt", models.BinaryField(max_length=32)),
                ("collector_init_code_hash", models.BinaryField(max_length=32)),
                (
                    "expected_collect_value_raw",
                    models.DecimalField(decimal_places=0, max_digits=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("broadcasted", "已广播"),
                            ("confirmed", "已确认"),
                            ("failed", "已失败"),
                            ("dropped", "已回退"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rpc_rejected", "节点拒绝"),
                            ("insufficient_balance", "余额不足"),
                            ("fee_too_low", "手续费过低"),
                            ("execution_reverted", "链上执行回退"),
                            (
                                "expected_transfer_missing",
                                "链上执行成功但预期资产移动缺失",
                            ),
                            ("utxo_conflict", "UTXO 冲突"),
                            ("double_spend", "双花冲突"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_deploy_collection",
                        to="chains.broadcasttask",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chains.chain"
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                    ),
                ),
                (
                    "deployer_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chains.address"
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_deploy_collection",
                        to="chains.onchaintransfer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="X402Facilitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorization_from_address",
                    common.fields.EvmAddressField(
                        db_index=True, max_length=42, verbose_name="授权方"
                    ),
                ),
                (
                    "authorization_to_address",
                    common.fields.EvmAddressField(
                        db_index=True, max_length=42, verbose_name="收款方"
                    ),
                ),
                (
                    "authorization_value_raw",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=32,
                        verbose_name="授权额度（最小单位）",
                    ),
                ),
                (
                    "valid_after",
                    models.PositiveBigIntegerField(verbose_name="生效起始时间"),
                ),
                (
                    "valid_before",
                    models.PositiveBigIntegerField(verbose_name="生效结束时间"),
                ),
                (
                    "authorization_nonce",
                    models.BinaryField(max_length=32, verbose_name="授权 nonce"),
                ),
                ("authorization_v", models.PositiveSmallIntegerField(verbose_name="v")),
                (
                    "authorization_r",
                    models.BinaryField(max_length=32, verbose_name="r"),
                ),
                (
                    "authorization_s",
                    models.BinaryField(max_length=32, verbose_name="s"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("broadcasted", "已广播"),
                            ("confirmed", "已确认"),
                            ("failed", "已失败"),
                            ("dropped", "已回退"),
                        ],
                        default="created",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rpc_rejected", "节点拒绝"),
                            ("insufficient_balance", "余额不足"),
                            ("fee_too_low", "手续费过低"),
                            ("execution_reverted", "链上执行回退"),
                            (
                                "expected_transfer_missing",
                                "链上执行成功但预期资产移动缺失",
                            ),
                            ("utxo_conflict", "UTXO 冲突"),
                            ("double_spend", "双花冲突"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="失败原因",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "broadcast_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x402_facilitation",
                        to="chains.broadcasttask",
                        verbose_name="广播任务",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chains.chain"
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                    ),
                ),
                (
                    "facilitator_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.address",
                        verbose_name="代付地址",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="x402_facilitation",
                        to="chains.onchaintransfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "x402 代付",
                "verbose_name_plural": "x402 代付",
            },
        ),
    ]
