# Generated by Django 5.2.12 on 2026-04-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicepayslot",
            name="project",
            field=models.ForeignKey(
                db_constraint=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="项目",
            ),
        ),
    ]
